I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Act1.rpy", line 85, in script
    hide Aangry1
Exception: Sayer 'D' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Act1.rpy", line 85, in script
    hide Aangry1
  File "C:\Users\donov\Downloads\renpy-7.1.1-sdk\renpy\ast.py", line 650, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\donov\Downloads\renpy-7.1.1-sdk\renpy\ast.py", line 560, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'D' is not defined.

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Disconnected 1.0
Thu Jun 27 13:05:40 2019
