I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/Act3.rpy", line 415, in script
    if ConDm == "Humor":
  File "game/Act3.rpy", line 415, in <module>
    if ConDm == "Humor":
NameError: name 'ConDm' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/Act3.rpy", line 415, in script
    if ConDm == "Humor":
  File "C:\Users\a2316\OneDrive\Desktop\Project Disconnected\renpy-7.3.0-sdk\renpy\ast.py", line 1830, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\a2316\OneDrive\Desktop\Project Disconnected\renpy-7.3.0-sdk\renpy\python.py", line 1990, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\a2316\OneDrive\Desktop\Project Disconnected\renpy-7.3.0-sdk\renpy\python.py", line 1983, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/Act3.rpy", line 415, in <module>
    if ConDm == "Humor":
NameError: name 'ConDm' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.0.271
Disconnected 0.63
Sat Jun 29 00:38:29 2019
